### ISSUE TITLE
@types definition in dependencies instead of devDependency

### ISSUE THREAD

**Issue by ccontour** [mongodb-js/mongodb-connection-string-url#15]
https://github.com/mongodb-js/mongodb-connection-string-url/blob/f9306a10d882309fddc050f9f9571aaf793a63f7/package.json#L59

**Comment by addaleax** [comment]
As mentioned in #18, users of this package will need `@types/whatwg-url` because this package's own types depend on this. It's unfortunate that npm doesn't have a concept of "type dependencies" or similar, but right now, it is what it is.

**Comment by Jacolack** [comment]
> users of this package will need `@types/whatwg-url` because this package's own types depend on this

That's ok if package's own types depend on `mongodb-connection-string-url`, all dependencies _and_ devDependencies will be satisfied by simply running `npm i mongodb-connection-string-url`.

Check out the [definition of devDependencies](https://nodejs.dev/learn/npm-dependencies-and-devdependencies), no one will ever need `@types/whatwg-url` without also already having ts-node, and therefore they will never be in a production environment, and would have never called `npm i --production`.

Therefore no one needs `@types/whatwg-url` as a real dependency.

Therefore #18 should have been accepted: (`@types/whatwg-url` should be removed as a real dependency and added as a devDependency)

**Comment by addaleax** [comment]
@Jacolack I don’t think you understood why this being a simple devDependency would not work – devDependencies are not installed transitively, unlike regular dependencies. I can just quote myself again:

> It's unfortunate that npm doesn't have a concept of "type dependencies" or similar, but right now, it is what it is.

**Comment by iptq** [comment]
Yes it's unfortunate but on the other hand this is misusing the regular dependencies field, causing unnecessary bloat in prod environments. Until npm supports this I would still prefer having it declared in devDependencies, and adding an extra line in the mongodb package docs or something for developers (who should be reading docs instead of blindly downloading from npm anyway).

Another solution would just be to publish the types separately, with `@types`. This would be a cleaner solution since it means all the dependencies can be expressed correctly and developers can pull in what they want. I believe this means either the mongodb package needs to do that as well or this would need to be included in the mongodb package docs as well.

Another more hacky workaround is taking advantage of the fact that peer dependencies are automatically installed with typical npm install, but can be eliminated from prod builds with `--omit=peer`. But this isn't really what peer dependencies were made for so it's an icky solution.
