### ISSUE TITLE
Appears to be more strict checking of quotes

### ISSUE THREAD

**Issue by jhsware** [mongodb-js/mongodb-connection-string-url#16]
We had a mongodb connection string enclosed in `"..."` in an Ansible vault file. The quotes were escaped somewhere, probably by ansible) which causes mongodb-connection-string-url to throw an error on startup due to twi double quotes. Previously this worked fine.

Version with issue: 2.4.1
Version that worked fine: 2.0.0

To tests this, just pass a mongodb connection string enclosed in two double quotes `""...""`.

**Comment by addaleax** [comment]
@jhsware Can you clarify what exactly the expected behavior is? Are you using the MongoDB Node.js driver? We talked about this with the driver team, and consensus seemed to be that it is a bug if the connection string does not begin with `mongodb://` or `mongodb+srv://`. I don’t think we’d want to accept quotes that are added by accident, unless there is a strong reason to do so?

**Comment by jhsware** [comment]
@addaleax we have env vars that we have stored in an ansible-vault-encrypted file like this:
```
MONGODB_CONNECTION_STRING="mongodb://127.0.0.1:27017/scanned-exams"
```
(the actual connection string is an Azure-generated connection string)

When it is decrypted and inserted to our environment it turns into the string `""mongodb://127.0.0.1:27017/scanned-exams""`, which was accepted by mongodb-connection-string-url@2.0.0 but not by mongodb-connection-string-url@2.4.1.

I am not sure why or where the quotes are escaped, but I assume this is done as part of the pipeline that injects the env.vars and it is possible that it is custom code somewhere.

I haven't tested exactly what commit causes the breaking change and it might not have been intended behaviour to accept such strings, but they worked. It is quite possible that others run into similar issues.

**Comment by addaleax** [comment]
@jhsware Right -- but isn't what you want to do removing the extra quotes before you pass the connection string to the driver? Or are you saying that you expect the driver to strip extraneous quotes for you?

**Comment by jhsware** [comment]
@addaleax I want to be able to pass the string without modification because it makes the code more readable. And since the double quoted connection strings where accepted before I would like them to still work to avoid applications breaking on redeploy (yes, we use lock files, but this is a minor bump and could easily be included during regular version sanitation).

After the change we also had to swap two `@` chars to `%40` that Azure added for us. This also worked previously with the double quotes (might not be related to the removal of quotes though).

**Comment by addaleax** [comment]
@jhsware We talked about this with the Node.js driver team, and there was consensus among all of us that this was a bug fix rather than a true breaking change, i.e. it is correct that the driver does not an invalid connection string, even if that connection string is invalid in a limited way. We are generally expecting applications to provide valid connection strings to all drivers.

I'm sorry that this is not the resolution you were hoping for.

**Comment by jhsware** [comment]
@addaleax let's keep our fingers crossed that we are the only ones who are bit by this then.
